CREATE TABLE test_results (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    test_name VARCHAR2(100),
    expected_output VARCHAR2(100),
    actual_output VARCHAR2(100),
    test_status VARCHAR2(10),
    run_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP
);
